export const DEPARTMENTS = [
    "Finance",
    "IT",
    "Legal",
    "Marketing",
    "Customer Service",
    "Sales",
    "Recruiting",
    "Training and Development",
    "Compensation and Benefits",
    "Health and Safety",
    "HR Administration",
    "Performance Management",
    "Employee Relations"
];

export const CITIES = ["New York", "San Francisco", "Los Angeles", "Chicago", "Houston", "Philadelphia", "Phoenix", "San Antonio", "Dallas", "Austin", "Jacksonville", "San Jose", "Columbus", "Indianapolis", "Fort Worth", "Charlotte", "Detroit", "El Paso", "Memphis", "Seattle", "Denver", "Washington", "Boston", "Nashville", "Baltimore", "Oklahoma City", "Louisville", "Portland", "Las Vegas", "Milwaukee", "Albuquerque", "Tucson", "Fresno", "Sacramento", "Kansas City", "Mesa", "Atlanta", "Colorado Springs", "Miami", "Omaha", "Raleigh", "Long Beach", "Virginia Beach", "Oakland", "Minneapolis", "Tulsa", "Arlington", "New Orleans", "Wichita", "Honolulu", "Cleveland", "Aurora", "Santa Ana", "Riverside", "Corpus Christi", "St. Louis", "Lexington", "Anchorage", "Pittsburgh", "Newark", "Plano", "Bakersfield", "Buffalo", "Fort Wayne", "Henderson", "Chandler", "Greensboro", "Lincoln", "St. Petersburg", "Glendale", "Chula Vista", "Orlando", "Jersey City", "Fort Lauderdale", "Norfolk", "Durham", "Madison", "Laredo", "Winston-Salem", "Garland", "Reno", "Richmond", "San Bernardino", "Boise", "Chesapeake", "Gilbert", "Scottsdale", "North Las Vegas", "Fremont", "Baton Rouge", "San Diego", "Spokane", "Modesto", "Tacoma", "Oxnard", "Irvine", "Hialeah"];

export const TABLE_HEADER = {
    "jobs": ["JOB TITLE", "LOCATION", "TYPE", "APPLICATION NO.", "PUBLISHED AT", "STATUS"]
} as { [key: string]: string[] };

export const TABLE_HEADER_MAP = {
    "jobs": ["name", "location", "type", "application_count", "created_at", "status"]
} as { [key: string]: string[] };

export const SYSTEM_TEMPLATES: Omit<
    EmailTemplateDTO,
    "_id" | "organizationId" | "createdAt" | "updatedAt"
>[] = [
        {
            templateId: "interview_invite",
            name: "Interview Invitation",
            subject: "You're invited to interview for {{jobTitle}}",
            body: `Hi {{candidateName}},\n\nWe're excited to invite you to interview for the {{jobTitle}} role at {{companyName}}.\n\nPlease use the scheduling link we'll send separately to pick a time that works for you.\n\nBest regards,\n{{senderName}}\n{{companyName}} Talent Team`,
            isDefault: true,
            isSystem: true,
        },
        {
            templateId: "application_submitted",
            name: "Application Received",
            subject: "We received your application for {{jobTitle}}",
            body: `Hi {{candidateName}},\n\nThank you for applying for {{jobTitle}} at {{companyName}}. We've received your application and our team will review it shortly.\n\nWe typically respond within 5–7 business days.\n\nBest,\nThe {{companyName}} Talent Team`,
            isDefault: true,
            isSystem: true,
        },
        {
            templateId: "application_rejected",
            name: "Application Update",
            subject: "Update on your application for {{jobTitle}}",
            body: `Hi {{candidateName}},\n\nThank you for your interest in the {{jobTitle}} role at {{companyName}}. After careful review, we've decided to move forward with other candidates at this time.\n\nWe appreciate the time you invested and wish you the best in your search.\n\nBest regards,\n{{companyName}} Talent Team`,
            isDefault: true,
            isSystem: true,
        },
        {
            templateId: "information_request",
            name: "Information Request",
            subject: "Quick follow-up on your application",
            body: `Hi {{candidateName}},\n\nThanks again for applying to {{jobTitle}}. Could you please share a bit more detail about {{topic}}?\n\nReply to this email at your convenience.\n\nThanks,\n{{senderName}}`,
            isDefault: true,
            isSystem: true,
        },
        {
            templateId: "interview_reminder",
            name: "Interview Reminder",
            subject: "Reminder: Interview for {{jobTitle}} on {{interviewDate}}",
            body: `Hi {{candidateName}},\n\nThis is a friendly reminder about your upcoming interview for {{jobTitle}} on {{interviewDate}}.\n\nIf you need to reschedule, please reply as soon as possible.\n\nSee you soon,\n{{companyName}} Talent Team`,
            isDefault: true,
            isSystem: true,
        },
    ];

// MARKETING SITE DATA
export const MOCK_JOBS = [
    {
        id: 'job-1',
        title: 'Senior Full-Stack Engineer',
        department: 'Engineering',
        location: 'Remote (US/EU)',
        type: 'Full-time',
        applicantCount: 46,
        screeningActive: true,
        idealProfile: {
            skills: ['TypeScript', 'React', 'Node.js', 'PostgreSQL', 'System Design'],
            minExperience: 5,
            requiredAnswers: ['Production high-scale DB experience', 'API design'],
        },
    },
    {
        id: 'job-2',
        title: 'Growth Marketing Manager',
        department: 'Marketing',
        location: 'New York / Hybrid',
        type: 'Full-time',
        applicantCount: 31,
        screeningActive: true,
        idealProfile: {
            skills: ['B2B SaaS', 'Paid Acquisition', 'SEO', 'Product-Led Growth', 'HubSpot'],
            minExperience: 4,
            requiredAnswers: ['Self-managed >$50k/mo ad budget', 'CAC payback analysis'],
        },
    },
    {
        id: 'job-3',
        title: 'Lead Product Designer',
        department: 'Design',
        location: 'San Francisco, CA',
        type: 'Full-time',
        applicantCount: 22,
        screeningActive: true,
        idealProfile: {
            skills: ['Figma', 'Design Systems', 'UX Research', 'Micro-interactions'],
            minExperience: 6,
            requiredAnswers: ['0-to-1 B2B product launched', 'Design system maintainer'],
        },
    },
];

export const PIPELINE_STAGES = [
    {
        id: 'applied',
        title: 'Inbox',
        description: 'New incoming resumes & applications',
        color: 'border-slate-300 text-slate-700 bg-slate-50',
        count: 14,
    },
    {
        id: 'screening',
        title: 'Auto-Screened',
        description: 'AI-evaluated against role rubric',
        color: 'border-amber-400 text-amber-800 bg-amber-50',
        count: 8,
    },
    {
        id: 'interview_hold',
        title: 'Interview Hold',
        description: 'Holds placed on hiring manager calendar',
        color: 'border-blue-400 text-blue-800 bg-blue-50',
        count: 5,
    },
    {
        id: 'team_round',
        title: 'Panel & Loops',
        description: 'Active team interview stages',
        color: 'border-purple-400 text-purple-800 bg-purple-50',
        count: 3,
    },
    {
        id: 'offer',
        title: 'Offer Stage',
        description: 'Verbal & written offer management',
        color: 'border-emerald-500 text-emerald-800 bg-emerald-50',
        count: 2,
    },
];

export const INITIAL_CANDIDATES = [
    {
        id: 'cand-1',
        name: 'Elena Rostova',
        role: 'Senior Full-Stack Engineer',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        appliedDate: 'Yesterday',
        source: 'LinkedIn',
        score: 96,
        stage: 'screening',
        skills: ['TypeScript', 'React 19', 'PostgreSQL', 'Docker', 'Next.js'],
        experienceYears: 6,
        currentCompany: 'Fintech Series B (Finscale)',
        summary: 'Lead architect behind payment microservices. Exceptional architecture track record and clear communication.',
        aiHighlights: [
            'Engineered sub-50ms distributed cache reducing database contention by 40%',
            'Exceeds 5-year technical threshold with strong modern TypeScript chops',
            'Strong open-source contributor with 2.4k GitHub stars',
        ],
        aiFlags: ['Currently on notice period; ready in 2 weeks'],
        notesCount: 4,
        unreadEmail: false,
    },
    {
        id: 'cand-2',
        name: 'Marcus Vance',
        role: 'Senior Full-Stack Engineer',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        appliedDate: '2 days ago',
        source: 'Referral',
        score: 92,
        stage: 'interview_hold',
        skills: ['Node.js', 'React', 'AWS', 'GraphQL', 'PostgreSQL'],
        experienceYears: 7,
        currentCompany: 'Northwind Software',
        summary: 'Senior engineer referred by Sarah (VP Eng). Built real-time collaboration engines for collaborative document editors.',
        aiHighlights: [
            'Direct referral from internal leadership (High trust signal)',
            'Extensive WebSocket and sync engine experience aligns 100% with roadmap',
        ],
        aiFlags: [],
        interviewHoldStatus: 'Held on Calendar',
        scheduledTime: 'Tomorrow at 2:00 PM EST',
        notesCount: 6,
        unreadEmail: true,
    },
    {
        id: 'cand-3',
        name: 'Aisha Patel',
        role: 'Senior Full-Stack Engineer',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        appliedDate: 'Today, 9:14 AM',
        source: 'Careers Page',
        score: 88,
        stage: 'applied',
        skills: ['React', 'TypeScript', 'Tailwind', 'Go', 'Redis'],
        experienceYears: 5,
        currentCompany: 'CloudMetric Inc.',
        summary: 'Strong frontend focus with solid backend knowledge. Redesigned customer onboarding flow increasing conversion by 28%.',
        aiHighlights: [
            'High domain relevance in SaaS dashboard performance',
            'Clear, quantified metrics provided in application responses',
        ],
        aiFlags: ['Go backend background rather than primary Node, but quick study'],
        notesCount: 1,
        unreadEmail: false,
    },
    {
        id: 'cand-4',
        name: 'Julian Hayes',
        role: 'Senior Full-Stack Engineer',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        appliedDate: '3 days ago',
        source: 'Indeed',
        score: 94,
        stage: 'team_round',
        skills: ['TypeScript', 'Kubernetes', 'FastAPI', 'PostgreSQL', 'React'],
        experienceYears: 8,
        currentCompany: 'Apex Health Systems',
        summary: 'Completed technical take-home with clean architecture. Staff interviewer gave 5/5 score on system design loop.',
        aiHighlights: [
            'Perfect 5/5 on async architecture code challenge',
            'Positive candidate feedback on interview loop pace',
        ],
        aiFlags: [],
        interviewHoldStatus: 'Confirmed',
        scheduledTime: 'Thursday, 3:30 PM EST',
        notesCount: 8,
        unreadEmail: false,
    },
    {
        id: 'cand-5',
        name: 'Chloe Tremblay',
        role: 'Senior Full-Stack Engineer',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
        appliedDate: '5 days ago',
        source: 'LinkedIn',
        score: 98,
        stage: 'offer',
        skills: ['TypeScript', 'React', 'Node.js', 'Distributed Systems'],
        experienceYears: 7,
        currentCompany: 'Stripe alumni / Freelance',
        summary: 'Final executive alignment complete. Offer letter drafted at $175k base + 0.25% equity.',
        aiHighlights: [
            'Exceptional culture fit and engineering excellence across all 4 interviewers',
            'Ready to accept pending remote equipment stipend confirmation',
        ],
        aiFlags: [],
        notesCount: 11,
        unreadEmail: false,
    },
    {
        id: 'cand-6',
        name: 'Devon Miller',
        role: 'Senior Full-Stack Engineer',
        avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
        appliedDate: '4 hours ago',
        source: 'LinkedIn',
        score: 64,
        stage: 'applied',
        skills: ['PHP', 'jQuery', 'WordPress', 'MySQL'],
        experienceYears: 3,
        currentCompany: 'Freelance Agency',
        summary: 'Primarily agency CMS development background. Lacks modern TypeScript and complex full-stack production architecture experience.',
        aiHighlights: ['Diligent work ethic and strong client communication'],
        aiFlags: [
            'Missing core technical requirement: TypeScript & modern React',
            'Years of experience (3) below senior threshold (5+)',
        ],
        notesCount: 0,
        unreadEmail: false,
    },
];
