import type {Metadata} from "next";
import {Geist_Mono, Inter, Ubuntu_Mono } from "next/font/google";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";

const geistSans = Inter({
    variable: "--font-inter-sans",
    subsets: ["latin"],
});

const geistMono = Ubuntu_Mono({
         variable: "--font-ubuntu-mono",
        weight: ["400", "700"]
    });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
